webApp/app/__init__.py
from flask_bootstrap import Bootstrap
from flask import Flask
from decouple import config
from config import config_dict

bootstrap = Bootstrap()

def create_app():
    app = Flask(__name__)

    app.config.from_object(config_dict[config("FLASK_ENV")])

    bootstrap.init_app(app)
    
    from app.main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    return app

webApp/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from app.main import views

webApp/app/main/views.py
from flask import (
    render_template,
    session,
    redirect,
    url_for,
    abort,
    flash,
    request,
    current_app,
    make_response)
from app.main import main
import pandas as pd
import numpy as np
import json
import time
import math

@main.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')

@main.route('/predict', methods=['GET', 'POST'])
def predict():
    start_time = time.time()
    if request.method == 'POST':
        id = request.form['id']

    print("##########################   START   ##########################")
    print(time.time() - start_time, "seconds")

    df_train = pd.read_csv("C:\\Users\\Paul_\\Desktop\\Projet Machine Learning\\Données\\application_train.csv")
    df_test = pd.read_pickle("C:\\Users\\Paul_\\Desktop\\Projet Machine Learning\\Données\\my_test.pickle")
    print(df_test)
    # Récupération des predicts
    test_id =  df_test['ID'].tolist()
    test_target =  df_test['TARGET'].tolist()
    test_proba =  df_test['PROBA'].tolist()
    print(type(test_id[0]))
    print(type(id))
    list_test = []
    for idx in range(len(test_id)) :
        if test_id[idx] == int(id) :
            list_test.append(test_id[idx])
            list_test.append(test_target[idx])
            list_test.append(test_proba[idx])
    list_test[2][0] = list_test[2][0] * 100
    list_test[2][1] = list_test[2][1] * 100

    print("##########################   CSV OPENED   ##########################")
    print(time.time() - start_time, "seconds")

    # On récupère le row correspondant à l'ID
    prospect = df_train.loc[df_train['SK_ID_CURR'] == int(id)]
    
    # On récupère les valeurs nécessaires à la réalisation des différents graphiques en itérant sur le pickle
    chart1, chart2, chart3, chart4 = [], [], [], []

    col_target = df_train['TARGET'].tolist()
    col_contract = df_train['NAME_CONTRACT_TYPE'].tolist()
    col_ext2 = df_train['EXT_SOURCE_2'].tolist()
    col_ext3 = df_train['EXT_SOURCE_3'].tolist()
    col_db = df_train['DAYS_BIRTH'].tolist()
    col_amtCred = df_train['AMT_CREDIT'].tolist()

    for idx in range(len(col_target)) :
        chart1.append([col_target[idx], col_contract[idx]])
        chart2.append([col_ext2[idx], col_ext3[idx]])
        chart3.append([col_target[idx], abs(col_db[idx])])
        chart4.append([col_target[idx], col_amtCred[idx]])

    print("##########################   GET COLUMNS DONE   ##########################")
    print(time.time() - start_time, "seconds")

    # CHART SUR LES TYPES DE PRÊTS
    # On récupère le type de prêt que fait le prospect testé
    prospectLoan = list(prospect.to_dict()['NAME_CONTRACT_TYPE'].values())[0]

    # On récupère le nombre de prêts remboursés ou non en fonction du type de prêt
    cash_r_0, cash_c_0, cash_c_1, cash_r_1 = 0, 0, 0, 0
    for item in chart1:
        if item[1] == "Cash loans" : 
            if item[0] == 0 :
                cash_c_0 += 1
            else :
                cash_c_1 += 1
        elif item[1] == "Revolving loans" :
            if item[0] == 0 :
                cash_r_0 += 1
            else :
                cash_r_1 += 1
    
    # On crée le json qui va être envoyé au javascript via Jinja
    mod_chart1 = json.dumps({ "array1" : [['Loan Type', 'Paid', 'Didn\'t pay'], ['Cash Loans', cash_c_0, cash_c_1], ['Revolving loans', cash_r_0, cash_r_1]] })
    
    # CHART SUR LES EXT_SOURCES
    # On récupère les valeurs du prospect
    prospectExt2 = list(prospect.to_dict()['EXT_SOURCE_2'].values())[0]
    prospectExt3 = list(prospect.to_dict()['EXT_SOURCE_3'].values())[0]

    # On calcule les valeurs moyennes pour EXT_SOURCE_2 et EXT_SOURCE_3
    meanExt2, meanExt3 = 0, 0
    chart2Ext2, chart3Ext3 = [], []
    for item in chart2:
        if item[0] :
            chart2Ext2.append(item[0])
        if item[1] :
            chart3Ext3.append(item[1])
    
    meanExt2 = np.nanmean(chart2Ext2)
    meanExt3 = np.nanmean(chart3Ext3)

    # On crée le json qui va être envoyé au javascript via Jinja en fonction des données que l'on as sur le prospect
    if not math.isnan(prospectExt2) and not math.isnan(prospectExt3) :
        mod_chart2 = json.dumps({ "array1" : [['Ext Source', 'Prospect Score', 'Average Score'], ['Ext Source 2', prospectExt2, meanExt2], ['Ext Source 3', prospectExt3, meanExt3]]})
    elif not math.isnan(prospectExt3) and math.isnan(prospectExt2) :
        mod_chart2 = json.dumps({ "array1" : [['Ext Source', 'Prospect Score', 'Average Score'], ['Ext Source 3', prospectExt3, meanExt3]]})
    else :
        mod_chart2 = json.dumps({ "array1" : [['Ext Source', 'Prospect Score', 'Average Score'], ['Ext Source 2', prospectExt2, meanExt2]]})
    
    # CHART SUR DAYS_BIRTH
    # On récupère le nombre de jours vécus du prospect
    prospectDB = abs(list(prospect.to_dict()['DAYS_BIRTH'].values())[0])
    
    # Moyennes des jours vécus des clients du csv
    ages0, ages1 = [], []
    for item in chart3:
        if item[0] == 0 :
            ages0.append(item[1])
        else :
            ages1.append(item[1])

    meanDb0 = np.nanmean(ages0)
    meanDb1 = np.nanmean(ages1)
    
    # On crée le json qui va être envoyé au javascript via Jinja
    mod_chart3 = json.dumps({ "array1" : [['Days Lived', 'Average of payeurs', 'Average of bad payeurs', 'Prospect'], [' ', meanDb0, meanDb1, prospectDB]]})

    # CHART ON AMT_CREDIT
    # On récupère le montant du prêt du prospect
    prospectCT = list(prospect.to_dict()['AMT_CREDIT'].values())[0]
    
    # On récupère la médiane des montants de prêts
    cT0, cT1 = [], []
    for item in chart4:
        if item[0] == 0 :
            cT0.append(item[1])
        else :
            cT1.append(item[1])

    meanCt0 = np.median(cT0)
    meanCt1 = np.median(cT1)

    # On crée le json qui va être envoyé au javascript via Jinja
    mod_chart4 = json.dumps({ "array1" : [['Credit Amount', 'Average of payeurs', 'Average of bad payeurs', 'Prospect'], [' ', meanCt0, meanCt1, prospectCT]]})

    print("##########################   ALL MOD CHARTS   ##########################")
    print(time.time() - start_time, "seconds")

    return render_template('predict.html', id=id, mod_chart1=mod_chart1, prospectLoan=prospectLoan, mod_chart2=mod_chart2, mod_chart3=mod_chart3, mod_chart4=mod_chart4, list_test=list_test)

webApp/app/templates/base.html
{% extends "bootstrap/base.html" %} {% block title %}Bills{% endblock %} {% block head %} {{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Index</a>
        </div>
    </div>
</div>
{% endblock %} {% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button> {{ message }}
    </div>
    {% endfor %} {% block page_content %}{% endblock %}
</div>
{% endblock %} {% block scripts %} {{ super() }}
{% endblock %}

webApp/app/templates/index.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %}

<title>{% block title %}User{% endblock %}</title>

{% block page_content %}

<div class="page-header">
    <h1>Choix du dossier</h1>
    <br><br>
    <form method="post" action="{{ url_for('main.predict') }}">
        <div class="form-group">
            <label>Numéro de dossier</label>
            <select id="id" name="id" placeholder="Numéro de dossier">
                <option value="194194">194194</option>
                <option value="114516">114516</option>
                <option value="152689">152689</option>
                <option value="164011">164011</option>
                <option value="127325">127325</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>



{% endblock %} {% block scripts %} {{ super() }} {% endblock %}

webApp/app/templates/predict.html
{% extends "base.html" %} {% import "bootstrap/wtf.html" as wtf %}

<title>{% block title %}Boule de Cristal{% endblock %}</title>

{% block page_content %}

<h1>Predict for user : {{ id }}</h1>
<!--condition sur le predict pour dire si valide ou non-->
{% if list_test[1] == 0 %}
    <h2>Prospect is <strong>viable</strong></h2>
    <h3>IA is {{ list_test[2][0] }}% sure.</h3>
{% endif %}
{% if list_test[1] == 1 %}
    <h2>Prospect is <strong>not viable</strong></h2>
    <h3>IA is {{ list_test[2][1] }}% sure.</h3>
{% endif %}
<br>
<br>
<hr>
<h4>Prospect is in the <strong>{{ prospectLoan }}</strong> category</h4>
<div id="barchart_material" style="width: 900px; height: 500px;"></div>
<hr>
<!--Chart des réponses en fonction des EXT_SOURCE_2 et EXT_SOURCE_3-->
<div id="barchart_material2" style="width: 900px; height: 500px;"></div>
<hr>
<!--Chart réprésentant la moyenne des DAYS_BIRTH de ceux qui paye et pareil pour ceux qui payent pas et donner le DAYS_BIRTH du prospect en test-->
<div id="barchart_material3" style="width: 900px; height: 500px;"></div>
<hr>
<!--le crédit term avg de ceux qui payent et ceus qui payent pas et le credit term du prospect test-->
<div id="barchart_material4" style="width: 900px; height: 500px;"></div>
<hr>

{% endblock %}

{% block scripts %} {{ super() }}


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    // CHART SUR LES TYPES DE PRETS
    var mod_chart1 = {{ mod_chart1 | safe }};
    console.log(mod_chart1.array1)
    //console.log(chart1.split())
    google.charts.load('current', {
        'packages': ['bar']
    });
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = google.visualization.arrayToDataTable(mod_chart1.array1);

        var options = {
            chart: {
                title: 'Types of loans',
                subtitle: 'Get money back from type of loan',
            },
            bars: 'vertical' // Required for Material Bar Charts.
        };

        var chart = new google.charts.Bar(document.getElementById('barchart_material'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
    }


    // CHART SUR LES EXT_SOURCES
    var mod_chart2 = {{ mod_chart2 | safe }};
    console.log(mod_chart2.array1)
    //console.log(chart1.split())
    google.charts.load('current', {
        'packages': ['bar']
    });
    google.charts.setOnLoadCallback(drawChart2);

    function drawChart2() {
        var data = google.visualization.arrayToDataTable(mod_chart2.array1);

        var options = {
            chart: {
                title: 'External Sources',
                subtitle: 'Prospect score VS average scores from external source(s)',
            },
            bars: 'horizontal' // Required for Material Bar Charts.
        };

        var chart = new google.charts.Bar(document.getElementById('barchart_material2'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
    }

    // CHART SUR LES DAYS_BIRTH avg
    var mod_chart3 = {{ mod_chart3 | safe }};
    console.log(mod_chart3.array1)
    //console.log(chart1.split())
    google.charts.load('current', {
        'packages': ['bar']
    });
    google.charts.setOnLoadCallback(drawChart3);

    function drawChart3() {
        var data = google.visualization.arrayToDataTable(mod_chart3.array1);

        var options = {
            chart: {
                title: 'Days Lived',
                subtitle: 'Prospect\'s age VS average age in days',
            },
            bars: 'vertical' // Required for Material Bar Charts.
        };

        var chart = new google.charts.Bar(document.getElementById('barchart_material3'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
    }


    // CHART SUR LES CREDIT_TERM avg
    var mod_chart4 = {{ mod_chart4 | safe }};
    console.log(mod_chart4.array1)
    //console.log(chart1.split())
    google.charts.load('current', {
        'packages': ['bar']
    });
    google.charts.setOnLoadCallback(drawChart4);

    function drawChart4() {
        var data = google.visualization.arrayToDataTable(mod_chart4.array1);

        var options = {
            chart: {
                title: 'Credit Amount',
                subtitle: 'Prospect\'s VS average',
            },
            bars: 'vertical' // Required for Material Bar Charts.
        };

        var chart = new google.charts.Bar(document.getElementById('barchart_material4'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
    }
</script>
{% endblock %}